
var firstname="Zara";
var lastname="Khan";
console.log(firstname);
console.log(lastname);
var fullname=firstname.concat(lastname);
console.log(fullname);
var a = 10;
var b = 20;
console.log(a);
console.log(b);
var add = a+b;
console.log(add);
var square_root=Math.sqrt(1024);
console.log(square_root);
var maxnumber=Math.max(876, 146, 347);
console.log(maxnumber);
var minnumber=Math.min(876, 146, 347);
console.log(minnumber);
var power=Math.pow(27, 5);
console.log(power);